name: schedulify
description: Schedule Template App Made in Flutter by Anita Balotiya.
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  # to display progress widgets based on percentage
  percent_indicator: ^4.2.3

  # to make http request
  http: ^1.2.1

  # for date formatting
  intl: ^0.19.0

  # flutter animation
  flutter_animate: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

  # Use to change package name
  # change_app_package_name: ^1.1.0 # flutter pub run change_app_package_name:main com.new.package.name

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato.ttf
